apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.5
          command:
            - "/opt/keycloak/bin/kc.sh"
            - "start-dev"
            - "--import-realm"
          env:
            - name: KEYCLOAK_ADMIN
              value: "user"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "password"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-postgres-service:5432/keycloak
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: password
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-realm-volume
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: keycloak-realm-volume
          configMap:
            name: keycloak-realm-configmap
