apiVersion: apps/v1
kind: Deployment
metadata:
  name: playback-service
spec:
  template:
    spec:
      containers:
        - name: playback-service
          env:
            - name: R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: playback-r2dbc-secret
                  key: username
            - name: R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: playback-r2dbc-secret
                  key: password
      volumes:
        - name: playback-config-volume
          configMap:
            name: playback-service-config
