apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - r2dbc-secret.yaml

configMapGenerator:
  - name: playback-service-config
    behavior: merge
    files:
      - application-prod.yml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: playback-service
