x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  snserver-db:
    image: postgres:15-alpine
    networks:
      - sn-network
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    logging: *logging
  mongo-db:
    image: mongo
    restart: always
    networks:
      - sn-network
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - .mongo_data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
#  migrations:
#    image: flyway/flyway
#    networks:
#      - eb-network
#    volumes:
#      - ./flyway/migrations:/flyway/sql
#    depends_on:
#      mysql-db:
#        condition: service_healthy
#    environment:
#      FLYWAY_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
#      FLYWAY_USER: ${MYSQL_USER}
#      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
#    command: migrate

networks:
  sn-network:
    external: true