apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-catalog-service
  labels:
    app: media-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-catalog-service
  template:
    metadata:
      labels:
        app: media-catalog-service
    spec:
      serviceAccountName: media-catalog-sa
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: media-catalog-service
          image: ghcr.io/sglee487/loopin-server/media-catalog-service
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.18.1.jar"
            - name: OTEL_SERVICE_NAME
              value: "media-catalog-service"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:4317"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
          volumeMounts:
            - name: media-catalog-config-volume
              mountPath: /workspace/config
      volumes:
        - name: media-catalog-config-volume
          configMap:
            name: media-catalog-service-config
