apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-catalog-service
  labels:
    app: media-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-catalog-service
  template:
    metadata:
      labels:
        app: media-catalog-service
    spec:
      containers:
      - name: media-catalog-service
        image: ghcr.io/sglee487/loopin-server/media-catalog-service:latest
        ports:
        - containerPort: 8080 # TODO: Change port if needed
