apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-catalog-service
  labels:
    app: media-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-catalog-service
  template:
    metadata:
      labels:
        app: media-catalog-service
    spec:
      serviceAccountName: media-catalog-sa
      imagePullSecrets:
        - name: ghcr-creds
      containers:
      - name: media-catalog-service
        image: ghcr.io/sglee487/loopin-server/media-catalog-service:ba9107386514a9507b08f85ed3679aa5b0bfd37a
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        volumeMounts:
        - name: media-catalog-config-volume
          mountPath: /workspace/config
      volumes:
      - name: media-catalog-config-volume
        configMap:
          name: media-catalog-service-config
