apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - media-catalog-sa.yaml
  - media-catalog-rbac.yaml

configMapGenerator:
  - name: media-catalog-service-config
    files:
      - application.yml
