apiVersion: v1
kind: Service
metadata:
  name: media-catalog-service
spec:
  selector:
    app: media-catalog-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # TODO: Change port if needed
