version: "3.8"
name: loopin-system

services:
  # Backing Services
  loopin-postgres:
    image: "postgres:14.12"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  loopin-keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - 59020:8080

  keycloak-postgres:
    image: "postgres:14.12"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/keycloak-data:/var/lib/postgresql/data
    ports:
      - 5433:5432 # Use a different port to avoid conflict with loopin-postgres

  loopin-redis:
    image: "redis:8.0.2"
    ports:
      - 6379:6379

  loopin-media-catalog-redis:
    image: "redis:8.0.2"
    ports:
      - 56371:6379