spring:
  main:
    # Disable the embedded web server so the application terminates after the CommandLineRunner completes
    web-application-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

management:
  health:
    redis:
      enabled: false 