spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: sn_server_spring
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: ${MONGODB_URL}
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_URL}
logging:
  level:
    site.sg.snserver_spring: debug
