spring:
  application:
    name: sn_server_spring
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb
      auto-index-creation: true