server:
  port: 59011
  shutdown: graceful
  netty:
    connection-timeout: 5s
    idle-timeout: 30s

spring:
  application:
    name: youtube-fetcher-service

youtube:
  api-key: ${YOUTUBE_DATA_API_KEY}
