server:
  port: 59011
  shutdown: graceful
  netty:
    connection-timeout: 5s
    idle-timeout: 30s

spring:
  application:
    name: youtube-fetcher-service
  config:
    import: "optional:kubernetes:"

youtube:
  api-key: ${YOUTUBE_DATA_API_KEY}
logging:
  level:
    com.loopin.youtube_fetcher_service: debug
