server:
  port: ${SERVER_PORT:59011}
  shutdown: graceful
  netty:
    connection-timeout: 5s
    idle-timeout: 30s

spring:
  application:
    name: youtube-fetcher-service
  config:
    import: "optional:kubernetes:"

youtube:
  api-key: ${YOUTUBE_DATA_API_KEY}
logging:
  level:
    com.loopin.youtube_fetcher_service: debug

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, gateway, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}