server:
  port: ${SERVER_PORT:59000}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4012}


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 2000
            response-timeout: 5s
            pool:
              max-life-time: 60s
              max-idle-time: 15s
              type: elastic
          routes:
            #        - id: spa-route
            #          uri: ${SPA_URL:http://localhost:9004}
            #          predicates:
            #            - Path=/,/*.css,/*.js,/favicon.ico
            - id: playback-route
              uri: ${PLAYBACK_SERVICE_URL:http://localhost:59002}
              predicates:
                - Path=/api/v1/user-play-session/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: playbackCircuitBreaker
                    fallbackUri: forward:/playback-fallback
            - id: media-catalog-route
              uri: ${MEDIA_CATALOG_SERVICE_URL:http://localhost:59001}
              predicates:
                - Path=/api/v1/playlists/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: mediaCatalogCircuitBreaker
                    fallbackUri: forward:/media-catalog-fallback
          default-filters:
            - SaveSession
            - TokenRelay
            - name: Retry
              args:
                retries: 3
                methods: GET
                series: SERVER_ERROR
                exceptions: java.io.IOException, java.util.concurrent.TimeoutException
                backoff:
                  firstBackoff: 50ms
                  maxBackOff: 500ms
                  factor: 2
                  basedOnPreviousValue: false
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: 'http://localhost:1420'
                allow-credentials: true
                allowedHeaders: '*'
                allowedMethods: '*'

  session:
    timeout: 10m
    redis:
      namespace: loopin:gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway-service
            client-secret: Pa7pQ5t2pN7YqDYcCjmMeFWGBOy9EyUL
            scope: openid,roles
        provider:
          keycloak:
            issuer-uri: http://localhost:59020/realms/loopin
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
    instances:
      mediaCatalogCircuitBreaker:
        timeoutDuration: 60s
        cancelRunningFuture: false
logging:
  group:
    circuitbreaker: io.github.resilience4j, org.springframework.cloud.circuitbreaker
  level:
    circuitbreaker: info
    org.springframework.security: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, gateway, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,redis
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}