apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backing-services.yaml
  - gateway-service.yaml
  - media-catalog-service.yaml
  - playback-service.yaml
  - youtube-fetcher-service.yaml
