apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  template:
    spec:
      volumes:
        - name: gateway-config-volume
          configMap:
            name: gateway-service-config
