apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - playback-sa.yaml
  - playback-rbac.yaml
  - configmap.yaml

configMapGenerator:
  - name: playback-service-config
    files:
      - application.yml
