apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
      - name: gateway-service
        image: ghcr.io/sglee487/loopin-server/gateway-service:12d6979b1f2efe16f7ff5f7b1896c87355df3b42
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: gateway-keycloak-client-secret
              key: client-secret
        volumeMounts:
        - name: gateway-config-volume
          mountPath: /workspace/config
      volumes:
      - name: gateway-config-volume
        configMap:
          name: gateway-service-config
      serviceAccountName: gateway-sa
