apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
      - name: gateway-service
        image: ghcr.io/sglee487/loopin-server/gateway-service:633b25c8120bbd134b92911b5a44166f3535b3cf
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.18.1.jar"
        - name: OTEL_SERVICE_NAME
          value: "gateway-service"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo.monitoring.svc.cluster.local:4317"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: gateway-keycloak-client-secret
              key: client-secret
        envFrom:
          - configMapRef:
              name: gateway-service-config
        volumeMounts:
        - name: gateway-config-volume
          mountPath: /workspace/config
      volumes:
      - name: gateway-config-volume
        configMap:
          name: gateway-service-config
      serviceAccountName: gateway-sa
