apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - gateway-rbac.yaml
  - gateway-sa.yaml

configMapGenerator:
  - name: gateway-service-config
    files:
      - application.yml
