version: "3.8"
name: loopin-system

services:
  # Backing Services
  loopin-postgres:
    image: "postgres:14.12"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  loopin-keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 59020:8080

  loopin-redis:
    image: "redis:8.0.2"
    ports:
      - 6379:6379