apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-fetcher-service
  labels:
    app: youtube-fetcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-fetcher-service
  template:
    metadata:
      labels:
        app: youtube-fetcher-service
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
      - name: youtube-fetcher-service
        image: ghcr.io/sglee487/loopin-server/youtube-fetcher-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: YOUTUBE_DATA_API_KEY
          valueFrom:
            secretKeyRef:
              name: youtube-api-key-secret
              key: api-key
        volumeMounts:
        - name: youtube-fetcher-config-volume
          mountPath: /workspace/config
      volumes:
      - name: youtube-fetcher-config-volume
        configMap:
          name: youtube-fetcher-service-config
