apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-fetcher-service
  labels:
    app: youtube-fetcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-fetcher-service
  template:
    metadata:
      labels:
        app: youtube-fetcher-service
    spec:
      serviceAccountName: youtube-fetcher-sa
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: youtube-fetcher-service
          image: ghcr.io/sglee487/loopin-server/youtube-fetcher-service:6e162381ba722862cbb6f9cbd8e0d63fda17aa27
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          envFrom:
            - secretRef:
                name: youtube-api-key-secret
            - configMapRef:
                name: youtube-fetcher-config
          volumeMounts:
            - name: youtube-fetcher-config-volume
              mountPath: /workspace/config
      volumes:
        - name: youtube-fetcher-config-volume
          configMap:
            name: youtube-fetcher-service-config
