apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - youtube-fetcher-sa.yaml
  - youtube-fetcher-rbac.yaml

configMapGenerator:
  - name: youtube-fetcher-service-config
    files:
      - application.yml
