name: Gateway Service CI

on:
  push:
    branches: [ '**' ]
    paths: [ 'gateway-service/**' ]
  pull_request:
    paths: [ 'gateway-service/**' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER: sglee487
  IMAGE_NAME: loopin-server/gateway-service   # ← (3) 이미지 경로
  VERSION: ${{ github.sha }}

jobs:
  ci:
    runs-on: ubuntu-22.04
    defaults: { run: { working-directory: gateway-service } }   # ← (2) 워킹 디렉터리
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Unit & integration tests
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Source scan (Anchore / Grype)
        uses: anchore/scan-action@v3
        id: src-scan
        with:
          path: .
          fail-build: false
          severity-cutoff: high
      - name: Upload SARIF (src)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.src-scan.outputs.sarif }}
          category: anchore-src
      # ───────────────────────────────────────
      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build image (local only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          BP_OCI_SOURCE: https://github.com/${{ github.repository }}
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage \
            --imageName ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: Tag latest & push both tags
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker tag ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
                     ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest
          docker push --all-tags ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}
      - name: Scan image (Anchore / Grype)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: anchore/scan-action@v3
        id: img-scan
        with:
          image: ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          fail-build: false
          severity-cutoff: high
      - name: Upload SARIF (image)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.img-scan.outputs.sarif }}
          category: anchore-image
