server:
  port: 8080
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: media-catalog-service
  cache:
    type: redis
  data:
    redis:
      host: loopin-media-catalog-redis
      port: 6379
      repositories:
        enabled: off
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
  reactor:
    context-propagation: auto
  r2dbc:
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}
    url: r2dbc:postgresql://loopin-postgres:5432/loopin_media_catalog
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://loopin-postgres:5432/loopin_media_catalog
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.loopin.bid/realms/loopin

bucket4j:
  enabled: true
  cache-to-use: redis-lettuce
  filters:
    - cache-name: buckets
      filter-method: webflux
      filter-order: 350
      url: /api/v1/playlists/youtube/.*
      rate-limits:
        - execute-condition: "headers.getFirst('X-Username') != 'admin'"
          execute-predicates:
            - METHOD=POST,PATCH
          cache-key: >
            headers.getFirst('X-Username')
              ?: #request.remoteAddress?.address?.hostAddress
          bandwidths:
            - capacity: 5
              time: 1
              unit: days
              refill-speed: interval

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
  level:
    com.giffing.bucket4j: trace

loopin:
  youtube-service-uri: "http://youtube-fetcher-service"
