apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-catalog-service
spec:
  selector:
    matchLabels:
      app: media-catalog-service
  template:
    spec:
      containers:
        - name: media-catalog-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: media-catalog-r2dbc-secret
                  key: username
            - name: R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: media-catalog-r2dbc-secret
                  key: password
      volumes:
        - name: media-catalog-config-volume
          configMap:
            name: media-catalog-service-config
