apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cronjob-youtube-sync.yaml
images:
  - name: ghcr.io/sglee487/loopin-server/media-catalog-service
    newTag: 9055db816599fb2f6bbc6e9ce77a408920e99204 # CI will replace this tag with the commit SHA or desired version
configMapGenerator:
  - name: media-catalog-service-config
    behavior: merge
    files:
      - application-prod.yml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: media-catalog-service
