apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/sglee487/loopin-server/media-catalog-service
    newTag: 6e162381ba722862cbb6f9cbd8e0d63fda17aa27 # CI will replace this tag with the commit SHA or desired version
configMapGenerator:
  - name: media-catalog-service-config
    behavior: merge
    files:
      - application-prod.yml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: media-catalog-service
