cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:"http://localhost:8080"}

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_URL}

#storage:
#  name: ${STORAGE_NAME}
#  prefix: ${STORAGE_PREFIX}
